# Generated by Django 2.1.8 on 2019-09-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_auto_20190909_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='type_picture',
            field=models.ImageField(default='images/1.jpg', upload_to='buyer/images'),
            preserve_default=False,
        ),
    ]
